urlybird/bookmarks/urls.py
from django.conf.urls import url
from . import views as bviews


urlpatterns = [
    url(r'^worms/(?P<pk>\d+)$',
        bviews.ClickListView.as_view(), name='click_list'),

    url(r'^worms/add$', bviews.add_worm, name='add_worm'),

    url(r'^birds/(?P<pk>\d+)$',
        bviews.BirdListView.as_view(), name='bird_list'),

    url(r'^birds/pop/(?P<pk>\d+)$',
        bviews.BirdPopListView.as_view(), name='bird_pop_list'),

    url(r'^delete/(?P<worm_id>\d+)', bviews.delete_worm, name='delete_worm'),

    url(r'^edit/(?P<worm_id>\d+)', bviews.edit_worm, name='edit_worm'),

    url(r'^popall$', bviews.PopAllListView.as_view(), name='popall_worms'),

    url(r'^pop30$', bviews.Pop30ListView.as_view(), name='pop30_worms'),

    url(r'^popbirds$', bviews.TopBirdsListView.as_view(), name='top_birds'),

    url(r'^$', bviews.WormListView.as_view(), name='recent_worms'),

    url(r'^(?P<slink>[A-Za-z0-9]{7})$',
        bviews.redirect_slink, name='redirect_slink'),

    # url(r'^worms/graph$',
    #     bviews.LineChartJSONView.as_view(), name='line_chart_json'),

    url(r'^worms/graph$',
        bviews.TemplateView.as_view(template_name='bookmarks/line_chart.html'),
        name='line_chart'),

]

urlybird/urlybird/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from bookmarks import urls as bookmark_urls
from bookmarks import views as bviews


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login$', bviews.user_login, name='user_login'),
    url(r'^logout$', bviews.user_logout, name='user_logout'),
    url(r'^register$', bviews.user_register, name='user_register'),
    url(r'', include(bookmark_urls)),
]

urlybird/bookmarks/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.


class Worm(models.Model):
    flink = models.TextField(max_length=2000)  # full url
    slink = models.CharField(max_length=7)  # short url
    user = models.ForeignKey(User, null=True, blank=True)
    timestamp = models.DateTimeField()
    wtitle = models.CharField(max_length=100)
    winfo = models.CharField(max_length=255, null=True, blank=True)
    numclicks = models.PositiveIntegerField(null=True, blank=True)

    def save(self):
        self.flink = self.flink.strip()
        super(Worm, self).save()

    def __str__(self):
        return self.slink


class Click(models.Model):
    user = models.ForeignKey(User, null=True, blank=True)
    worm = models.ForeignKey(Worm)
    timestamp = models.DateTimeField()

    def save(self):
        super(Click, self).save()
        self.worm.numclicks = self.worm.click_set.all().count()
        self.worm.save()

    def __str__(self):
        return '{} at {}'.format(self.worm, self.timestamp)

urlybird/bookmarks/views.py
from datetime import datetime, timedelta
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.shortcuts import redirect, render, get_object_or_404
from django.utils.timezone import make_aware
from urlybird.forms import UserForm, WormForm
from django.db.models import Count
from django.views import generic
from .models import Worm, Click
from faker import Faker
from django.contrib.auth.decorators import login_required


# Create your views here.

class WormListView(generic.ListView):
    template_name = 'bookmarks/recent_worms.html'
    context_object_name = 'worms'
    paginate_by = 25

    def get_queryset(self):
        self.form = WormForm()
        return Worm.objects.all().order_by('-timestamp') \
            .prefetch_related('user')


class PopAllListView(generic.ListView):
    template_name = 'bookmarks/popall_worms.html'
    context_object_name = 'worms'
    paginate_by = 25

    def get_queryset(self):
        self.form = WormForm()
        return Worm.objects.order_by('-numclicks')


class Pop30ListView(generic.ListView):
    template_name = 'bookmarks/pop30_worms.html'
    context_object_name = 'worms'
    paginate_by = 25

    def get_queryset(self):
        self.form = WormForm()
        last30 = datetime.now() - timedelta(days=30)
        thirtyworms = Worm.objects.filter(timestamp__gt=last30)
        return thirtyworms.order_by('-numclicks')


class TopBirdsListView(generic.ListView):
    template_name = 'bookmarks/top_birds.html'
    context_object_name = 'birds'
    paginate_by = 25

    def get_queryset(self):
        self.form = WormForm()
        return User.objects.annotate(bird_clicks=Count('click')).order_by('-bird_clicks')


class BirdListView(generic.ListView):
    template_name = 'bookmarks/bird_list.html'
    context_object_name = 'worms'
    paginate_by = 25

    def get_queryset(self):
        self.form = WormForm()
        self.user = get_object_or_404(User, pk=self.kwargs['pk'])
        return self.user.worm_set.all().order_by('-timestamp') \
            .prefetch_related('user')


class BirdPopListView(generic.ListView):
    template_name = 'bookmarks/bird_pop_list.html'
    context_object_name = 'worms'
    paginate_by = 25

    def get_queryset(self):
        self.form = WormForm()
        self.user = get_object_or_404(User, pk=self.kwargs['pk'])
        last30 = datetime.now() - timedelta(days=30)
        thirtybird = self.user.worm_set.all().filter(timestamp__gt=last30)
        return thirtybird.order_by('-numclicks') \
            .prefetch_related('user')


class ClickListView(generic.ListView):
    model = Click
    template = 'bookmarks/click_list.html'
    context_object_name = 'clicks'
    paginate_by = 25

    def get_context_data(self, **kwargs):
        context = super(ClickListView, self).get_context_data(**kwargs)
        context['worm'] = Worm.objects.get(pk=self.kwargs['pk'])
        return context

    def get_queryset(self):
        return Click.objects.filter(worm=Worm.objects.get(
            pk=self.kwargs['pk'])).order_by('-timestamp') \
            .prefetch_related('worm', 'user')


def home(request):
    return render(request, 'bookmarks/home.html')


def add_worm(request):
    if request.method == 'POST':
        form = WormForm(request.POST)
        if form.is_valid():
            worm = form.save(commit=False)
            if request.user.is_authenticated():
                worm.user = request.user
            fake = Faker()
            while True:
                slink = fake.password(length=7, special_chars=False)
                if len(Worm.objects.filter(slink=slink)) == 0:
                    worm.slink = slink
                    break
                continue
            worm.timestamp = make_aware(datetime.now())
            worm.save()
            messages.add_message(request,
                                 messages.SUCCESS,
                                 'You successfully got that worm!')
        else:
            messages.add_message(request,
                                 messages.ERROR,
                                 'Form data invalid, all fields required')
    else:
        messages.add_message(request,
                             messages.ERROR,
                             'Stop trying to hack this site!')
    return redirect(request.GET['next'])


def redirect_slink(request, slink):
    worm = get_object_or_404(Worm, slink=slink)
    click = Click(worm=worm, timestamp=make_aware(datetime.now()))
    if request.user.is_authenticated():
        click.user = request.user
    click.save()
    return redirect(worm.flink.strip())


def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None and user.is_active:
            login(request, user)
            return redirect(reverse('bird_list', args=[user.pk]))
        else:
            messages.add_message(request, messages.ERROR, 'ERROR LOGGING IN!')
            return render(request,
                          'bookmarks/user_login.html',
                          {'username': username})
    else:
        return render(request, 'bookmarks/user_login.html')


def user_register(request):
    if request.method == 'POST':
        form = UserForm(request.POST)

        if form.is_valid():
            user = form.save()
            password = form['password']
            user.set_password(password)
            user.save()

            user = authenticate(username=user.username, password=password)
            login(request, user)
            messages.add_message(request,
                                 messages.SUCCESS,
                                 'Your account was successfully created.')
            return redirect('bird_list', user.pk)
    else:
        form = UserForm()
    return render(request,
                  'bookmarks/user_register.html',
                  {'form': form})


def user_logout(request):
    if request.user.is_authenticated():
        user_name = request.user.username
        logout(request)
        messages.add_message(request, messages.SUCCESS,
                             "{}, you have successfully logged out".format(
                                 user_name))
        return redirect('/')


@login_required
def delete_worm(request, worm_id):
    if Worm.objects.get(pk=worm_id).user == request.user:
        Worm.objects.get(pk=worm_id).delete()
        messages.add_message(request, messages.SUCCESS, "Worm removed")
        return redirect('bird_list', pk=request.user.pk)
    else:
        messages.add_message(
            request, messages.ERROR, "You do not have access")
        return redirect('recent_worms')


@login_required
def edit_worm(request, worm_id):
    worm = get_object_or_404(Worm, pk=worm_id)
    if request.method == 'GET':
        form = WormForm(instance=worm)
    elif request.method == 'POST':
        form = WormForm(instance=worm, data=request.POST)
        if form.is_valid():
            worm = form.save(commit=False)
            worm.timestamp = datetime.now()
            worm.save()
            messages.add_message(request, messages.SUCCESS,
                                 'Updated worm')
            return redirect('click_list', pk=worm_id)
        messages.add_message(request,
                             messages.ERROR,
                             'Form data invalid'
                             'by field')
    return render(request,
                  'bookmarks/edit_worm.html', {'worm_id': worm_id,
                                               'worm': worm,
                                               'form': form})

urlybird/bookmarks/templates/bookmarks/bird_list.html
{% extends "add_base.html" %}
{% load bootstrap3 %}
{% block content %}

<body>

{% if worms %}
  <h2>{{ view.user.username }}'s Worms by Date</h2>

  <table class="table table-striped">
  <tr>
    <th>Inch Worm</th>
    <th></th>
    <th>Title</th>
    <th>Bird</th>
    <th>Date Created/Modified</th>
    <th>Clicks</th>
    <th></th>
  </tr>
  {% for worm in worms %}
    <tr>
      <td><b><a href="{% url 'redirect_slink' worm.slink %}">{{ worm.slink|ljust:10 }}</a></b></td>
      <td><a href="{% url 'click_list' worm.pk %}"><span class="glyphicon glyphicon-info-sign"></span></a>
        {% if user == view.user %}
          <a href="{% url 'edit_worm' worm.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
        {% endif %}
      </td>
      <td>{{ worm.wtitle|truncatechars:50 }}</td>
      {% if worm.user %}
        <td><a href="{% url 'bird_list' worm.user.pk %}">{{ worm.user }}</a></td>
      {% else %}
        <td>anonymous</td>
      {% endif %}
      <td><small>{{ worm.timestamp }} ({{ worm.timestamp | timesince }} ago)</small></td>
      <td>{{ worm.numclicks }}</td>
      {% if user == view.user %}
      <td><a href="{% url 'delete_worm' worm.pk %}"><span class="glyphicon glyphicon-trash"></span></a></td>
      {% endif %}
    </tr>
  {% endfor %}
  </table>

  {% if worms|length > 25 %}
    <div class="text-center">
      {% bootstrap_pagination page_obj pages_to_show=5 %}
    </div>
  {% endif %}

{% else %}
  <h2>{{ view.user.username }}</h2>
  <h4>You don't have any worms yet.<h4>
{% endif %}

{% endblock %}

urlybird/bookmarks/templates/bookmarks/bird_pop_list.html
{% extends "add_base.html" %}
{% load bootstrap3 %}
{% block content %}

<body>

{% if worms %}
  {% if user == view.user %}
    <h2>{{ view.user.username }}'s Worms by Popularity (30 Days)</h2>
    <table class="table table-striped">
    <tr>
      <th>Inch Worm</th>
      <th></th>
      <th>Title</th>
      <th>Bird</th>
      <th>Date Created/Modified</th>
      <th>Clicks</th>
      <th></th>
    </tr>
    {% for worm in worms %}
      <tr>
        <td><b><a href="{% url 'redirect_slink' worm.slink %}">{{ worm.slink|ljust:10 }}</a></b></td>
        <td><a href="{% url 'click_list' worm.pk %}"><span class="glyphicon glyphicon-info-sign"></span></a>
          {% if user == view.user %}
            <a href="{% url 'edit_worm' worm.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
          {% endif %}
        </td>
        <td>{{ worm.wtitle|truncatechars:50 }}</td>
        {% if worm.user %}
          <td><a href="{% url 'bird_list' worm.user.pk %}">{{ worm.user }}</a></td>
        {% else %}
          <td>anonymous</td>
        {% endif %}
        <td><small>{{ worm.timestamp }} ({{ worm.timestamp | timesince }} ago)</small></td>
        <td>{{ worm.numclicks }}</td>
        {% if worm.user %}
        <td><a href="{% url 'delete_worm' worm.pk %}"><span class="glyphicon glyphicon-trash"></span></a></td>
        {% endif %}
      </tr>
    {% endfor %}
    </table>

    {% if worms|length > 25 %}
      <div class="text-center">
        {% bootstrap_pagination page_obj pages_to_show=5 %}
      </div>
    {% endif %}
  {% endif %}
{% else %}
  <h2>{{ view.user.username }}</h2>
  <h4>You don't have any clicks to show.<h4>
{% endif %}

{% endblock %}

urlybird/bookmarks/templates/bookmarks/click_list.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block head %}
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
<script src="http://code.highcharts.com/highcharts.js"></script>
<script type="text/javascript" src="/js/themes/gray.js"></script>
{% endblock %}

{% block content %}

<body>
  <div class="row">
    <div class="col-md-8">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h1 class="panel-title"><b>Worm Details</b></h1>
        </div>
        <div class="panel-body">
          <p><b>Title: </b>{{ worm.wtitle }}
          <br>
          <b>Description: </b>{{ worm.winfo }}
          <br>
          {% if worm.user %}
          <b>Bird: </b><a href="{% url 'bird_list' worm.user_id %}">{{ worm.user.username }}</a>
          <br>
          {% endif %}
          <b>Inch Worm: <a href="{% url 'redirect_slink' worm.slink %}">{{worm.slink}}</a></b>
          <br>
          <b>Full Link: </b><a href="{% url 'redirect_slink' worm.slink %}">{{worm.flink}}</a>
          <br>
          <small> {{worm.timestamp}} - {{worm.timestamp | timesince}} ago&nbsp;&nbsp;
            {% if user.pk == worm.user_id %}
              <a href="{% url 'edit_worm' worm.pk %}"><span class="glyphicon glyphicon-pencil"></span></a> &nbsp;
              <a href="{% url 'delete_worm' worm.pk %}"><span class="glyphicon glyphicon-trash"></span></a>
            {% endif %}</small>
          </p>
        </div>
      </div>
    </div>
    <div class="col-md-4" id="container" style="width:30%; height:218px;"></div>
  </div>

{% if clicks %}
<br>
<table class="table table-striped">
<tr>
  <th>Click Date</th>
  <th>User</th>
</tr>
{% for click in clicks %}
  <tr>
    <td>{{ click.timestamp }} ({{ click.timestamp | timesince }} ago)</td>
    {% if click.user %}
    <td><a href="{% url 'bird_list' click.user.pk %}">{{ click.user }}</a></td>
    {% else %}
    <td>anonymous</td>
    {% endif %}
  </tr>
{% endfor %}
</table>
{% endif %}

{% if worm.numclicks > 25 %}
<div class="text-center">
  {% bootstrap_pagination page_obj pages_to_show=5 %}
</div>
{% endif %}
<script>
$(function () {
    $('#container').highcharts({
        chart: {
            type: 'line'
        },
        title: {
            text: 'Fruit Consumption'
        },
        xAxis: {
            categories: ['Apples', 'Bananas', 'Oranges']
        },
        yAxis: {
            title: {
                text: 'Fruit eaten'
            }
        },
        series: [{
            name: 'Jane',
            data: [1, 0, 4]
        }, {
            name: 'John',
            data: [5, 7, 3]
        }]
    });
});
</script>

{% endblock %}

urlybird/bookmarks/templates/bookmarks/edit_worm.html
{% extends "base.html" %}


{% block content %}
<h1>Edit Worm</h1>

<form method="POST" action="{% url 'edit_worm' worm_id %}">
  {% csrf_token %}
  <div class="row">
    <div class="col-md-8">
      <textarea class="form-control" cols="90" id="id_flink" maxlength="2000" name="flink" rows="1">{{ worm.flink }}</textarea>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-4">
      <textarea class="form-control" cols="40" id="id_wtitle" maxlength="100" name="wtitle" rows="1">{{ worm.wtitle }}</textarea>
      <br>
      <input type="submit" class="btn btn-md btn-primary" value="&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Submit edit!&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;">
    </div>
    <div class="col-md-4">
      <textarea class="form-control" cols="40" id="id_winfo" maxlength="255" name="winfo" rows="4">{{ worm.winfo }}</textarea>
    </div>
  </div>
</form>
{% endblock %}

urlybird/bookmarks/templates/bookmarks/home.html
{% load staticfiles %}
<!DOCTYPE html>
{% load bootstrap3 %}
{% load bootstrap_themes %}
{% bootstrap_styles theme='paper' type='min.css' %}
{% bootstrap_css %}
{% bootstrap_javascript jquery=True %}

<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}URLy Bird{% endblock %}</title>
  <link rel="stylesheet" type="text/css" href="{% static 'style2.css' %}" />
</head>
<body>



  <div class="site-wrapper">

        <div class="site-wrapper-inner">

          <div class="cover-container">

            <div class="masthead clearfix">
              <div class="inner">
                <h3 class="masthead-brand">URLy Bird</h3>
                <nav>
                  <ul class="nav masthead-nav">
                  {% if user.is_authenticated %}
                    <li><a href="{% url 'bird_list' user.pk %}">{{ user.username }}</a></li>
                    <li><a href="{% url 'user_logout' %}">Logout</a></li>
                  {% else %}
                    <li><a href="{% url 'user_login' %}">Login</a></li>
                    <li><a href="{% url 'user_register' %}">Register</a></li>
                  {% endif %}
                  </ul>
                </nav>
              </div>
            </div>

            <div class="inner cover">
              <h1 class="cover-heading">Catch a worm.</h1>
              <br>
              <p class="lead">Welcome to URLy bird! <br> URLy Bird is the one-stop shop <br> for all your URL shortening and tracking needs.<br> We take your hard-to-remember URLs <br> and return an easy to use "worm." <br> Click below to get started. </p>
              <p class="lead">
                <br>
                <a href="{% url 'recent_worms' %}" class="btn btn-lg btn-default">Get Started</a>
              </p>
            </div>




</body>
<footer>
<div class="mastfoot">
            <div class="pull-right">
              <p><small>&copy;2015 Adam Hartz and Tyler Kotkin</small></p>
            </div>
          </div>
</footer>
</html>

urlybird/bookmarks/templates/bookmarks/line_chart.html
{% extends "base.html" %}
{% load staticfiles %}
<html>
    <head>
        <title>django-chartjs line chart demo</title>
        <!--[if lte IE 8]>
            <script src="{% static 'js/excanvas.js' %}"></script>
        <![endif]-->
    </head>
    <body>
        <h1>Some Line Charts loaded in Ajax!</h1>

        <canvas id="myChart" width="500" height="400"></canvas>

        <script type="text/javascript" src="http://code.jquery.com/jquery-1.10.0.min.js"></script>
        <script type="text/javascript" src="{% static 'js/Chart.min.js' %}"></script>
        <script type="text/javascript">
            $.get('{% url "line_chart_json" %}', function(data) {
                var ctx = $("#myChart").get(0).getContext("2d");
                new Chart(ctx).Line(data);
            });
        </script>
    </body>
</html>

urlybird/bookmarks/templates/bookmarks/pop30_worms.html
{% extends "add_base.html" %}
{% load bootstrap3 %}
{% block content %}

<body>

<h2>Worms by Popularity (30 Days)</h2>

<table class="table table-striped">
<tr>
  <th>Inch Worm</th>
  <th></th>
  <th>Title</th>
  <th>Bird</th>
  <th>Date Created/Modified</th>
  <th>Clicks</th>
</tr>
{% for worm in worms %}
  <tr>
    <td><b><a href="{% url 'redirect_slink' worm.slink %}">{{ worm.slink }}</a></b></td>
    <td><a href="{% url 'click_list' worm.pk %}"><span class="glyphicon glyphicon-info-sign"></span></a></td>
    <td>{{ worm.wtitle|truncatechars:50 }}</td>
    {% if worm.user %}
      <td><a href="{% url 'bird_list' worm.user.pk %}">{{ worm.user }}</a></td>
    {% else %}
      <td>anonymous</td>
    {% endif %}
    <td><small>{{ worm.timestamp }} ({{ worm.timestamp | timesince }} ago)</small></td>
    <td>{{ worm.numclicks }}</td>
  </tr>
{% endfor %}
</table>

<div class="text-center">
  {% bootstrap_pagination page_obj pages_to_show=5 %}
</div>
{% endblock %}

urlybird/bookmarks/templates/bookmarks/popall_worms.html
{% extends "add_base.html" %}
{% load bootstrap3 %}
{% block content %}

<body>

<h2>Most Popular of All-Time</h2>

<table class="table table-striped">
<tr>
  <th>Inch Worm</th>
  <th></th>
  <th>Title</th>
  <th>Bird</th>
  <th>Date Created/Modified</th>
  <th>Clicks</th>
</tr>
{% for worm in worms %}
  <tr>
    <td><b><a href="{% url 'redirect_slink' worm.slink %}">{{ worm.slink }}</a></b></td>
    <td><a href="{% url 'click_list' worm.pk %}"><span class="glyphicon glyphicon-info-sign"></span></a></td>
    <td>{{ worm.wtitle|truncatechars:50 }}</td>
    {% if worm.user %}
      <td><a href="{% url 'bird_list' worm.user.pk %}">{{ worm.user }}</a></td>
    {% else %}
      <td>anonymous</td>
    {% endif %}
    <td><small>{{ worm.timestamp }} ({{ worm.timestamp | timesince }} ago)</small></td>
    <td>{{ worm.numclicks }}</td>
  </tr>
{% endfor %}
</table>

<div class="text-center">
  {% bootstrap_pagination page_obj pages_to_show=5 %}
</div>
{% endblock %}

urlybird/bookmarks/templates/bookmarks/recent_worms.html
{% extends "add_base.html" %}
{% load bootstrap3 %}
{% block content %}

<body>

<h2>Recent Worms</h2>

<table class="table table-striped">
<tr>
  <th>Inch Worm</th>
  <th></th>
  <th>Title</th>
  <th>Bird</th>
  <th>Date Created/Modified</th>
  <th>Clicks</th>
</tr>
{% for worm in worms %}
  <tr>
    <td><b><a href="{% url 'redirect_slink' worm.slink %}">{{ worm.slink }}</a></b></td>
    <td><a href="{% url 'click_list' worm.pk %}"><span class="glyphicon glyphicon-info-sign"></span></a></td>
    <td>{{ worm.wtitle|truncatechars:50 }}</td>
    {% if worm.user %}
      <td><a href="{% url 'bird_list' worm.user.pk %}">{{ worm.user }}</a></td>
    {% else %}
      <td>anonymous</td>
    {% endif %}
    <td><small>{{ worm.timestamp }} ({{ worm.timestamp | timesince }} ago)</small></td>
    <td>{{ worm.numclicks }}</td>
  </tr>
{% endfor %}
</table>

<div class="text-center">
  {% bootstrap_pagination page_obj pages_to_show=5 %}
</div>
{% endblock %}

urlybird/bookmarks/templates/bookmarks/top_birds.html
{% extends "add_base.html" %}
{% load bootstrap3 %}
{% block content %}

<body>

<h2>Birds by Popularity</h2>

<table class="table table-striped">
<tr>
  <th>Bird</th>
  <th></th>
  <th>Clicks</th>
</tr>
{% for bird in birds %}
  <tr>
    <td><b><a href="{% url 'bird_list' bird.pk %}">{{ bird.username }}</a></b></td>
    <td></td>
    <td>{{ bird.bird_clicks }}</td>
  </tr>
{% endfor %}
</table>

<div class="text-center">
  {% bootstrap_pagination page_obj pages_to_show=5 %}
</div>
{% endblock %}

urlybird/bookmarks/templates/bookmarks/user_login.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block title %}User Login Form{% endblock %}

{% block content %}

  <h2>Login</h2>

<form method="POST" action="{% url 'user_login' %}">
  {% csrf_token %}

  <div class="row">
    <div class="col-md-3">
      <input class="form-control" type="text" value="{{ username }}" cols="30" id="id_username" maxlength="30" name="username" rows="1" placeholder="Username"></input>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-3">
      <input class="form-control" type="password" value="{{ password }}" cols="30" id="id_password" maxlength="30" name="password" rows="1" placeholder="Password"></input>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-3">
      <input type="submit" class="btn btn-md btn-primary" value="Login">
    </div>
  </div>

</form>

{% endblock %}

urlybird/bookmarks/templates/bookmarks/user_register.html
{% extends "base.html" %}
{% block title %}User Registration{% endblock %}

{% block content %}
  <h2>Register</h2>

  <form method="POST" action="{% url 'user_register' %}">
    {% csrf_token %}
    <div class="row">
    <div class="col-md-4">
      <input class="form-control" cols="40" id="id_wtitle" maxlength="50" name="username" rows="1" placeholder="Username"></input>
    </div><br><br>
    </div>
    <div class="row">
      <div class="col-md-4">
      <input class="form-control" cols="40" id="id_wtitle" maxlength="50" name="email" rows="1" placeholder="Email"></input>
    </div><br><br>
    </div>
    <div class="row">
    <div class="col-md-4">
      <input class="form-control" cols="40" id="id_wtitle" maxlength="50" name="first_name" rows="1" placeholder="First Name"></input>
    </div><br><br>
    </div>
      <div class="row">
      <div class="col-md-4">
      <input class="form-control" cols="40" id="id_wtitle" maxlength="50" name="last_name" rows="1" placeholder="Last Name"></input>
    </div><br><br>
    </div>
    <div class="row">
    <div class="col-md-4">
      <input class="form-control" type="password" cols="40" id="id_wtitle" maxlength="50" name="password" rows="1" placeholder="Password"></input>




      <br>
      <input type="submit" class="btn btn-md btn-primary" value="&nbsp;&nbsp;Register!&nbsp;&nbsp;">
    </div>
  </div>

  </form>
{% endblock %}